### ISSUE TITLE
Deployment Target

### ISSUE THREAD

**Issue by nitrag** [jim-rhoades/DivingBoard#6]
Is there a reason you're requiring SDK > 11? It's always best to set it to at least -1 major version, especially if you don't need the latest features.

```
[!] CocoaPods could not find compatible versions for pod "DivingBoard":
  In Podfile:
    DivingBoard (~> 1.1)

Specs satisfying the `DivingBoard (~> 1.1)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by jim-rhoades** [comment]
Good call... I changed the deployment target to iOS 10.0 so it should work for apps that target iOS 10.0 or newer now (instead of iOS 11.2 or newer like it was before).
